fix: leaderelection uses the lock in the same ns as the controller
argoproj/argo-rollouts pull request #1717
Opened 2021-12-15 20:23 UTC by huikang

- by default, the lock is in argo-rollouts
- remove leader namespace from cli arguments

Signed-off-by: Hui Kang <hui.kang@salesforce.com>

close #1704 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

2021-12-17 07:41 UTC, jessesuen approved these changes

2021-12-18 02:02 UTC, jessesuen requested changes
It looks like every e2e test all time out. I suspect the controller is not actually starting properly after this change for some reason.

2021-12-18 03:43 UTC, huikang commented
> It looks like every e2e test all time out. I suspect the controller is not actually starting properly after this change for some reason.

Yeah, I think it is because the e2e cluster doesn't have the argo-rollouts` ns. Pushing a new commit to create the ns in e2e.

2021-12-18 04:46 UTC, huikang commented
@jessesuen , I think the failed tests are due to flakiness.

2021-12-21 19:12 UTC, jessesuen approved these changes

2021-12-21 19:13 UTC, merged