typo(examples/traffic-routing/istio-mirror.yaml): change `destkop` to…
argoproj/argo-rollouts pull request #2269
Opened 2022-09-27 09:41 UTC by daixijun

… `desktop`

Signed-off-by: Xijun Dai <daixijun1990@gmail.com>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

2022-11-17 23:01 UTC, zachaller approved these changes

2022-12-30 09:56 UTC, agrawroh requested changes
Wish we can get a basic spell-checker bot :D

2022-12-30 09:56 UTC, agrawroh approved these changes

2022-12-30 15:56 UTC, zachaller commented
> Wish we can get a basic spell-checker bot :D

We actually do but it seems to have some issues running within golang-lintci if I run it manually I get

``` 
find . -type f -name '*.*' | grep -v vendor/ | grep -v ui/node_modules | grep -v /server/static | grep -v ui/dist| xargs misspell -error
./my-manifests/dynamicStableScale/rollout.yaml:1:77: "destkop" is a misspelling of "desktop"
./CHANGELOG.md:7:53: "accross" is a misspelling of "across"
./hack/installers/install-codegen-go-tools.sh:9:2: "unecessary" is a misspelling of "unnecessary"
./docs/generated/notification-services/googlechat.md:89:48: "succesfully" is a misspelling of "successfully"
./docs/features/traffic-management/istio.md:315:28: "preferrably" is a misspelling of "preferably"
./docs/getting-started/appmesh/index.md:59:76: "configuraiton" is a misspelling of "configuration"
./docs/assets/versions.css:56:23: "overriden" is a misspelling of "overridden"
./docs/security.md:14:4: "vulnerabilites" is a misspelling of "vulnerabilities"
./examples/istio/istio-mirror.yaml:1:77: "destkop" is a misspelling of "desktop"
./CHANGELOG-v0.1.0_v1.1.0.md:106:41: "incorect" is a misspelling of "incorrect"
```

2026-06-15 13:43 UTC, kostis-codefresh commented
Included as part of https://github.com/argoproj/argo-rollouts/pull/4781

2026-06-16 08:58 UTC, closed without merging