fix(manifests): Add volume for plugin folder
argoproj/argo-rollouts pull request #3546
Opened 2024-04-30 07:09 UTC by tommy351

The latest manifests (v1.7.0-rc1) throws the following error during plugin download. The reason probably is the stricter security context introduced in #3424. I added a new volume for downloaded plugin files.

```
time="2024-04-30T06:38:26Z" level=fatal msg="Failed to download plugins: failed to create plugin folder for plugin (argoproj-labs/gatewayAPI): (mkdir /home/argo-rollouts/plugin-bin: read-only file system)"
```

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

2024-05-01 20:42 UTC, agaudreault requested changes

2024-05-03 10:57 UTC, tommy351 commented on manifests/base/argo-rollouts-deployment.yaml
> +          mountPath: /home/argo-rollouts/plugin-bin
Updated in da2dea5

2024-05-13 18:33 UTC, agaudreault requested changes

2024-05-13 18:33 UTC, agaudreault commented on manifests/base/argo-rollouts-deployment.yaml
> +        volumeMounts:
`tmp` volume added but not mounted.

2024-05-15 08:36 UTC, tommy351 commented on manifests/base/argo-rollouts-deployment.yaml
> +        volumeMounts:
Fixed in 64a30cc

2024-05-15 18:11 UTC, agaudreault approved these changes
LGTM

2024-06-17 14:14 UTC, merged