fix: fix slice init length
argoproj/argo-rollouts pull request #3868
Opened 2024-10-03 06:30 UTC by cuishuang

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/) with a list of types and scopes found [here](https://github.com/argoproj/argo-rollouts/blob/master/.github/workflows/pr-title-check.yml), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed my commits with [DCO](https://github.com/argoproj/argoproj)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

The intention here should be to initialize a slice with a capacity of 3 rather than initializing the length of this slice. 

The only demo: https://go.dev/play/p/q1BcVCmvidW

2025-02-19 06:56 UTC, cuishuang commented
friendly ping~

2025-10-30 16:28 UTC, cuishuang commented
@zachaller Hi, could you please review this PR? Thank you!

2026-05-25 13:19 UTC, kostis-codefresh commented
Is there an associated issue that shows what this PR is actually fixing?

2026-06-13 12:00 UTC, cuishuang commented
> Is there an associated issue that shows what this PR is actually fixing?

Thanks for your reply. You can read this issue for more information.  https://github.com/golang/go/issues/69872

2026-07-16 07:38 UTC, kostis-codefresh requested changes
Thanks for the clarification. Can you please fix the DCO check?

2026-07-17 15:15 UTC, cuishuang commented
> Thanks for the clarification. Can you please fix the DCO check?

Of course. Fixed. Please review it again.  @kostis-codefresh

2026-07-17 17:11 UTC, kostis-codefresh approved these changes

2026-07-17 17:12 UTC, merged