chore: Set preserveUnknownFields: false to prevent mistake
argoproj/argo-rollouts pull request #708
Opened 2020-09-08 03:14 UTC by mtsmfm

Setting `preserveUnknownFields: false` makes validation strict and can prevent nesting mistake like the following:

```yaml
strategy:
  # <= canary is missing!
  steps: [...]
```

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-rollouts/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
  * I think this is a chore
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

2020-09-08 03:17 UTC, mtsmfm commented
> * I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.

Is there any existing tests for CRD validation?
Sorry I'm not sure which test code I need to change.

2020-09-08 03:21 UTC, mtsmfm commented
> * My organization is added to [USERS.md](https://github.com/argoproj/argo-rollouts/blob/master/USERS.md).

Hmm, I can't find USERS.md. Should I create the file?

2020-09-22 07:37 UTC, jessesuen requested changes
Hi @mtsmfm the files you changed are auto-generated and shouldn't be modified directly since it will be lost on the next call to generate manifests. The right way would be to send the flag to the controller-gen tool here: https://github.com/argoproj/argo-rollouts/blob/master/hack/gen-crd-spec/main.go#L56-L60, and then re-run `make manifests`

2020-09-22 08:29 UTC, mtsmfm commented
@jessesuen Thank you for pointing out.
I've noticed `make codegen` doesn't work well.
I committed both codegen script fix and changing `preserveUnknownFields`.
Please feel free to ask me to split this PR if you want.

2020-09-23 09:08 UTC, jessesuen approved these changes

2020-09-23 09:10 UTC, merged

2020-09-23 09:12 UTC, jessesuen commented
Thanks for fixing the makefile too!

2020-09-30 20:03 UTC, jessesuen commented
Unfortunately, this change needs to be reverted:

The problem is, we had to remove validation of resource limits in the schema, because OpenAPI validation does not have proper support for things like ResourceQuantity.  When this is coupled with preserveUnknownFields, it has the side effect of dropping the limits.

2020-10-01 01:38 UTC, mtsmfm commented
@jessesuen 

> because OpenAPI validation does not have proper support for things like ResourceQuantity

Sorry, I'm not sure what `ResourceQuantity` means.
Can you give me example yaml?

2020-10-01 05:11 UTC, jessesuen commented
The following will longer work by setting `preserveUnknownFields: false`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: container-resource-formats
spec:
  aaaaa: aaaa
  selector:
    matchLabels:
      app: container-resource-formats
  template:
    metadata:
      labels:
        app: container-resource-formats
    spec:
      containers:
      - name: a
        image: nginx:1.19-alpine
        command: [sleep, infinity]
        resources:
          requests:
            cpu: 0.001
      - name: b
        image: nginx:1.19-alpine
        command: [sleep, infinity]
        resources:
          requests:
            cpu: '0.001'
      - name: c
        image: nginx:1.19-alpine
        command: [sleep, infinity]
        resources:
          requests:
            cpu: 1m
  strategy:
    canary: {}
```

Because we remove validation for these fields here:
https://github.com/argoproj/argo-rollouts/blob/master/hack/gen-crd-spec/main.go#L230-L261

The reason why we remove validation for it is because the generated OpenAPI schema validation cannot support the various `cpu:` formats.

2020-10-01 05:14 UTC, jessesuen commented
FYI, [the recent switch to use tolerant dynamic informers](https://github.com/argoproj/argo-rollouts/pull/666) actually drops unknown fields, so preserveUnknownFields is largely unnecessary in argo-rollouts as of v0.9.1. The controller will actually drop the fields when it persists the rollout.

2020-10-01 07:41 UTC, mtsmfm commented
> The controller will actually drop the fields when it persists the rollout.

Let's say we have the following YAML:

```yaml
strategy:
  canary: {}
  steps: # <= accidentally nested under strategy, not canary
    - setWeight: 50
    - pause: {}
```

In this case, `steps` is just dropped silently and the change will be rolled out 100%, right?

I'm proposing to set `preserveUnknownFields: false` to return an error from a server without applying the change in such a case.

2020-10-01 08:32 UTC, jessesuen commented
> In this case, steps is just dropped silently and the change will be rolled out 100%, right?

Correct, that is what would happen without `preserveUnknownFields: false`, so it's not the best solution.

> I'm proposing to set preserveUnknownFields: false to return an error from a server without applying the change in such a case.

I understand. If there was a way to do that while still allowing the example I pasted to work, then we can certainly add back `preserveUnknownFields: false`, but at the moment, `preserveUnknownFields: false` is not allow container resources to be set properly.

2020-10-01 08:42 UTC, mtsmfm commented
Thank you for your kindly explanation.
Now I understand we need to remove the hack (probably not only `removeK8S118Fields` but also `removeNestedItems`?)
and it's because of OpenAPI (or k8s CRD) limitation.

2020-10-01 10:44 UTC, jessesuen commented
> Now I understand we need to remove the hack (probably not only removeK8S118Fields but also removeNestedItems?)

The hack was added for a good reason. In PR https://github.com/argoproj/argo-rollouts/pull/752, I actually updated controller-gen to latest version to see if underlying issue was addressed in v0.4.1, and even attempted to remove the hack workarounds, including removing `removeK8S118Fields`, but it was still not working. The CRD generated by controller-gen v0.4.1 would not accept container resources in various formats.

You're welcome to try but I did not have any luck.